import { useState } from "react";

interface Project {
    title: string;
    description: string;
    tags: string[];
    link: string;
}

const ProjectCard = ({ project }: { project: Project }) => {
    const [isExpanded, setIsExpanded] = useState(false);

    return (
        <div className="group relative bg-card rounded-xl border border-border/50 p-6 hover:border-primary/50 transition-all duration-300 hover:shadow-lg hover:-translate-y-1">
            <div className="flex flex-col h-full">
                <h3 className="text-xl font-bold text-foreground mb-3 group-hover:text-primary transition-colors">
                    {project.title}
                </h3>
                <div className="mb-6 flex-grow">
                    <p className={`text-muted-foreground leading-relaxed ${isExpanded ? '' : 'line-clamp-3'}`}>
                        {project.description}
                    </p>
                    <button
                        onClick={() => setIsExpanded(!isExpanded)}
                        className="text-primary text-sm font-medium mt-2 hover:underline focus:outline-none"
                    >
                        {isExpanded ? "Show Less" : "Read More"}
                    </button>
                </div>
                <div className="flex flex-wrap gap-2 mb-6">
                    {project.tags.map((tag) => (
                        <span key={tag} className="text-xs font-medium px-2.5 py-1 rounded-md bg-secondary/10 text-secondary-foreground">
                            {tag}
                        </span>
                    ))}
                </div>
                <a href={project.link} className="inline-flex items-center text-sm font-semibold text-primary hover:text-primary/80 transition-colors mt-auto">
                    View Project
                    <svg className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                    </svg>
                </a>
            </div>
        </div>
    );
};

const Projects = () => {
    const projects = [
        {
            title: "Meows & Blogs – Cat-themed Web App",
            description: "Developed a dynamic single-page application offering curated news updates and a personalized blogging experience with a playful cat-themed interface. Implemented bookmarkable news articles fetched via API and an interactive blog creation system with image uploads and localStorage-based persistence.",
            tags: ["React.js", "CSS", "Axios", "Vite"],
            link: "https://meeshunini.github.io/Meows_And_Blogs/",
        },
        {
            title: "MeeshuNini Portfolio",
            description: "Designed and developed a visually engaging personal portfolio using handcrafted HTML, SCSS, and JavaScript. Implemented dynamic, cursor-responsive visual effects (including the \"neko\" cat follow cursor animation) and thematic styling for an interactive user experience.",
            tags: ["HTML", "SCSS", "JavaScript", "GitHubPages"],
            link: "#",
        },
        {
            title: "Current Affairs Web-Page",
            description: "Contributed to development of current affairs platform using modern web technologies including Next.js, React, TypeScript, and MongoDB.",
            tags: ["NextJs", "React", "TypeScript", "MongoDB"],
            link: "https://www.byolacademy.com/current-affairs",
        },
        {
            title: "AI vs Human Text Classification & Analysis",
            description: "Developed a supervised machine learning pipeline to classify whether text was authored by a human or generated by AI, leveraging linguistic, stylistic, and readability features. Performed exploratory data analysis (EDA) with visualizations of label distribution and word frequency patterns.",
            tags: ["Python", "scikit-learn", "XGBoost", "NLP", "Seaborn"],
            link: "#",
        },
        {
            title: "Personalized Course Recommendation System",
            description: "Designed and evaluated multiple recommender system approaches (content-based, clustering, collaborative filtering, and neural networks) on online course datasets. Built collaborative filtering models (item-based KNN, NMF), comparing performance with RMSE and qualitative insights.",
            tags: ["Python", "scikit-learn", "K-Means", "NMF"],
            link: "#",
        },
        {
            title: "No-Code ML Model Training App",
            description: "Developed an interactive Streamlit web app enabling dataset upload and automated ML model training without coding knowledge. Integrated preprocessing workflows with configurable model selection (Logistic Regression, Random Forest, XGBoost) and real-time evaluation metrics.",
            tags: ["Python", "Streamlit", "scikit-learn", "AutoML"],
            link: "#",
        },
    ];

    return (
        <section id="projects" className="section-padding bg-background">
            <div className="container-width">
                <h2 className="text-3xl font-bold text-foreground mb-16 text-center">Featured Projects</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {projects.map((project, index) => (
                        <ProjectCard key={index} project={project} />
                    ))}
                </div>
            </div>
        </section>
    );
};

export default Projects;
